#!/bin/bash
#
# Perform necessary collectd setup steps
# after package is installed.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}
chown -R root:root /opt/collectd
echo "Thank you for installing collectd!"

exit 0
